version: "3"
services:
  # databases
  redis:
    image: redis:6.2-alpine
    container_name: redis
    logging:
      driver: none
  mongodb:
    image: mongo:latest
    container_name: mongodb
    logging:
      driver: none

  # airline services
  american-airlines:
    build: american-airlines
    container_name: american-airlines
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DATABASE_HOST=redis
      - DATABASE_PORT=6379
    depends_on:
      - redis
  emirates:
    build: emirates
    container_name: emirates
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - DATABASE_NAME=emirates_flights
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    depends_on:
      - mongodb

