version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  emirates:
    build: emirates
    container_name: emirates
    ports:
      - 8083:8083
    environment:
      - SERVER_PORT=8083
      - DATABASE_NAME=emirates_flights
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    depends_on:
      - mongodb

