version: "3"
services:
  # databases
  redis:
    image: redis:6.2-alpine
    container_name: redis

  mongodb:
    image: mongo:latest
    container_name: mongodb

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  # central
  broker:
    build: broker
    container_name: broker
    ports: 
      - "8080:8080"
    environment:
      - SERVER_PORT=8080


  # airline services
  american-airlines:
    build: american-airlines
    container_name: american-airlines
    environment:
      - SERVER_PORT=8081
      - DATABASE_HOST=redis
      - DATABASE_PORT=6379
    depends_on:
      - redis

  cathay-pacific:
    build: cathay-pacific
    container_name: cathay-pacific
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  emirates:
    build: emirates
    container_name: emirates
    environment:
      - SERVER_PORT=8083
      - DATABASE_NAME=emirates_flights
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    depends_on:
      - mongodb

  ryan-air:
    build: ryan-air
    container_name: ryan-air
    environment:
      - SERVER_PORT=8084
      - DATABASE_NAME=ryanair_flights
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    depends_on:
      - mongodb
